version: "3.8"
services: 
  web:
    container_name: motherhood-beyond-bars-web 
    build:
      context: ./web
      target: dev
    restart: always
    command: yarn dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./web/:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
  
  mobile:
    container_name: motherhood-beyond-bars-mobile
    build:
      context: ./mobile
      target: dev
    restart: always
    command: npm start 
    platform: linux/amd64
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    volumes:
      - ./mobile/:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
